### ISSUE TITLE
Bug in config.json

### ISSUE THREAD

**Issue by tonythetigerttt** [plivo/plivo-examples-node#9]
You need to remove the last comma in the code, the trailing comma, or else it will break

**Comment by tsudot** [comment]
@tonythetigerttt which code file are you talking about? Could you please link to it in this issue?

**Comment by tsudot** [comment]
https://github.com/plivo/plivo-examples-node/commit/1d8c2f6bbeda13f2b4d95f8e8781907ecc9e72fa fixes it
